/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Test4_InventoryReportsFunction;

/**
 *
 * @author Raylen
 */
public class InvRep_Design extends javax.swing.JFrame {

    /**
     * Creates new form InvRep_Design
     */
    public InvRep_Design() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jCheckBox2 = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jCheckBox3 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Inventory Reports");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(148, 17, 93, 16);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Product", "Category", "Original Quantity", "Stock Bought", "Current Stocks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 50, 380, 190);

        jButton1.setText("Purchase");
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 440, 100, 23);

        jLabel2.setText("Product");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 310, 50, 16);

        jLabel3.setText("Price");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 310, 37, 16);

        jLabel4.setText("P 100");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 400, 50, 16);

        jLabel5.setText("P 1,000");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 340, 50, 16);

        jLabel6.setText("P 500");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 370, 50, 16);

        jLabel7.setText("Quantity");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(250, 310, 60, 16);

        jLabel8.setText("0");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(280, 400, 10, 16);

        jButton2.setText("-");
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 400, 20, 20);

        jButton3.setText("+");
        getContentPane().add(jButton3);
        jButton3.setBounds(290, 400, 20, 20);

        jButton4.setText("-");
        getContentPane().add(jButton4);
        jButton4.setBounds(250, 340, 20, 20);

        jButton5.setText("-");
        getContentPane().add(jButton5);
        jButton5.setBounds(250, 370, 20, 20);

        jButton6.setText("+");
        getContentPane().add(jButton6);
        jButton6.setBounds(290, 340, 20, 20);

        jButton7.setText("+");
        getContentPane().add(jButton7);
        jButton7.setBounds(290, 370, 20, 20);

        jLabel9.setText("0");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(280, 340, 10, 16);

        jLabel10.setText("0");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(280, 370, 10, 16);

        jLabel11.setText("Quantity Left");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(330, 310, 80, 16);

        jLabel12.setText("10");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(350, 400, 12, 16);

        jLabel13.setText("10");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(350, 340, 12, 16);

        jLabel14.setText("10");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(350, 370, 43, 16);

        jButton8.setText("Update Stock Quantity");
        getContentPane().add(jButton8);
        jButton8.setBounds(440, 460, 150, 23);

        jLabel15.setText("Update Stock Quantity");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(430, 290, 130, 16);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(430, 320, 71, 22);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cellphone", "Eyeshadow", "Notebook" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(430, 420, 100, 22);

        jLabel16.setText("Select Product Category:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(430, 350, 140, 16);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gadget", "Mkaeup", "School Supplies" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(430, 370, 130, 22);

        jLabel17.setText("Select Product:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(430, 400, 110, 16);

        jCheckBox1.setText("Cellphone");
        jScrollPane4.setViewportView(jCheckBox1);

        jTabbedPane2.addTab("tab3", jScrollPane4);

        jCheckBox2.setText("Eyeshadow");
        jScrollPane3.setViewportView(jCheckBox2);

        jTabbedPane2.addTab("tab2", jScrollPane3);

        jCheckBox3.setText("Notebook");
        jScrollPane2.setViewportView(jCheckBox3);

        jTabbedPane2.addTab("tab1", jScrollPane2);

        getContentPane().add(jTabbedPane2);
        jTabbedPane2.setBounds(10, 340, 150, 150);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvRep_Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvRep_Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvRep_Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvRep_Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvRep_Design().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
